export const ROLES = {
 SUPER_ADMIN: "ADMINSUPER",
  ADMIN: "ADMINSUPER",
  ENCARGADO: "ENCARGADO",
  USER: "USER",
};

export const PERMISSIONS = {
  ADMIN: ["*"],
 ADMINSUPER: ["*"],
  ENCARGADO: [
    "PROYECTOS",
    "CODIGO_PROYECTO",
    "DIRECTOR PROYECTO",
    "GERENTE PROYECTO",
    "DIRECTOR COMPRAS",
    "TÉCNICO RESPONSABLE ",
    "GERENTE GENERAL"
  ],

  USER: [
    "REQUERIMIENTOS",
    "LISTA_REQUERIMIENTOS",
  ],
};
